2021-03-13 19:44:18,657 INFO    MainThread:22372 [wandb_setup.py:_flush():69] setting env: {}
2021-03-13 19:44:18,657 INFO    MainThread:22372 [wandb_setup.py:_flush():69] setting login settings: {}
2021-03-13 19:44:18,657 INFO    MainThread:22372 [wandb_init.py:_log_setup():334] Logging user logs to C:\Users\Shriram\Documents\GitHub\DeepLearning\wandb\run-20210313_194418-1mjxbw9o\logs\debug.log
2021-03-13 19:44:18,658 INFO    MainThread:22372 [wandb_init.py:_log_setup():335] Logging internal logs to C:\Users\Shriram\Documents\GitHub\DeepLearning\wandb\run-20210313_194418-1mjxbw9o\logs\debug-internal.log
2021-03-13 19:44:18,659 INFO    MainThread:22372 [wandb_init.py:init():367] calling init triggers
2021-03-13 19:44:18,659 INFO    MainThread:22372 [wandb_init.py:init():372] wandb.init called with sweep_config: {}
config: {}
2021-03-13 19:44:18,680 INFO    MainThread:22372 [wandb_init.py:init():387] re-initializing run, found existing run on stack: 13a6m289
2021-03-13 19:44:18,682 INFO    MainThread:22372 [wandb_run.py:finish():1135] finishing run 0x2e4/cs6910-a1/13a6m289
2021-03-13 19:44:18,684 INFO    MainThread:22372 [jupyter.py:save_history():320] not saving jupyter history
2021-03-13 19:44:18,684 INFO    MainThread:22372 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-03-13 19:44:18,684 INFO    MainThread:22372 [wandb_init.py:_jupyter_teardown():266] cleaning up jupyter logic
2021-03-13 19:44:18,684 INFO    MainThread:22372 [wandb_run.py:_atexit_cleanup():1446] got exitcode: 0
2021-03-13 19:44:18,685 INFO    MainThread:22372 [wandb_run.py:_restore():1418] restore
2021-03-13 19:44:19,062 INFO    MainThread:22372 [wandb_run.py:_wait_for_finish():1568] got exit ret: file_counts {
  wandb_count: 1
  media_count: 10
}
pusher_stats {
  uploaded_bytes: 6154
  total_bytes: 6154
}

2021-03-13 19:44:21,077 INFO    MainThread:22372 [wandb_run.py:_wait_for_finish():1568] got exit ret: file_counts {
  wandb_count: 4
  media_count: 10
}
pusher_stats {
  uploaded_bytes: 12037
  total_bytes: 12037
}

2021-03-13 19:44:23,081 INFO    MainThread:22372 [wandb_run.py:_wait_for_finish():1568] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 4
  media_count: 10
}
pusher_stats {
  uploaded_bytes: 12037
  total_bytes: 12037
}

2021-03-13 19:44:24,892 INFO    MainThread:22372 [wandb_run.py:_show_summary():1723] rendering summary
2021-03-13 19:44:24,894 INFO    MainThread:22372 [wandb_run.py:_show_history():1761] rendering history
2021-03-13 19:44:24,900 INFO    MainThread:22372 [wandb_run.py:_show_files():1790] logging synced files
2021-03-13 19:44:24,912 INFO    MainThread:22372 [wandb_init.py:init():416] starting backend
2021-03-13 19:44:24,912 INFO    MainThread:22372 [backend.py:_multiprocessing_setup():69] multiprocessing start_methods=spawn, using: spawn
2021-03-13 19:44:24,928 INFO    MainThread:22372 [backend.py:ensure_launched():123] starting backend process...
2021-03-13 19:44:25,838 INFO    MainThread:22372 [backend.py:ensure_launched():127] started backend process with pid: 960
2021-03-13 19:44:25,838 INFO    MainThread:22372 [wandb_init.py:init():421] backend started and connected
2021-03-13 19:44:25,895 INFO    MainThread:22372 [wandb_init.py:init():461] updated telemetry
2021-03-13 19:44:25,895 INFO    MainThread:22372 [wandb_init.py:init():480] communicating current version
2021-03-13 19:44:29,534 INFO    MainThread:22372 [wandb_init.py:init():485] got version response upgrade_message: "wandb version 0.10.22 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-03-13 19:44:29,545 INFO    MainThread:22372 [wandb_init.py:init():493] communicating run to backend with 30 second timeout
2021-03-13 19:44:30,049 INFO    MainThread:22372 [wandb_init.py:init():518] starting run threads in backend
2021-03-13 19:44:35,079 INFO    MainThread:22372 [wandb_run.py:_console_start():1476] atexit reg
2021-03-13 19:44:35,081 INFO    MainThread:22372 [wandb_run.py:_redirect():1339] redirect: SettingsConsole.WRAP
2021-03-13 19:44:35,081 INFO    MainThread:22372 [wandb_run.py:_redirect():1374] Wrapping output streams.
2021-03-13 19:44:35,082 INFO    MainThread:22372 [wandb_run.py:_redirect():1390] Redirects installed.
2021-03-13 19:44:35,082 INFO    MainThread:22372 [wandb_init.py:init():542] run started, returning control to user process
2021-03-13 20:03:56,948 INFO    MainThread:22372 [wandb_run.py:_atexit_cleanup():1446] got exitcode: 0
2021-03-13 20:03:56,950 INFO    MainThread:22372 [wandb_run.py:_restore():1418] restore
2021-03-13 20:03:57,405 INFO    MainThread:22372 [wandb_run.py:_wait_for_finish():1568] got exit ret: file_counts {
  wandb_count: 1
  media_count: 11
}
pusher_stats {
  uploaded_bytes: 35534
  total_bytes: 35534
}

2021-03-13 20:03:59,525 INFO    MainThread:22372 [wandb_run.py:_wait_for_finish():1568] got exit ret: file_counts {
  wandb_count: 4
  media_count: 11
}
pusher_stats {
  uploaded_bytes: 41652
  total_bytes: 41652
}

2021-03-13 20:04:01,539 INFO    MainThread:22372 [wandb_run.py:_wait_for_finish():1568] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 4
  media_count: 11
}
pusher_stats {
  uploaded_bytes: 41652
  total_bytes: 41652
}

